# Generated by Django 4.1.3 on 2023-01-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Comunication_LTD", "0002_ns_user"),
    ]

    operations = [
        migrations.DeleteModel(name="NS_user",),
    ]
