# Generated by Django 4.1.3 on 2023-01-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Comunication_LTD", "0004_ns_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="custom_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
            ],
        ),
    ]
